name: Main
on: [push, pull_request]
jobs:
  test:
    name: Test all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.13.x"
          - "1.14.x"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.0
        with:
          go-version: ${{matrix.go}}
      - name: Check out code
        uses: actions/checkout@v2.3.1
      - name: Download modules
        run: go mod download
      - name: Test
        run: go test -v ./...
